# Liber Speech Interactive Setup Script (Windows PowerShell)
# Supports component selection, device configuration, model configuration, environment variable generation

param(
    [switch]$SkipPrompt,
    [string]$ConfigFile = ".env"
)

$ErrorActionPreference = "Stop"

function Write-ColorText {
    param([string]$Text, [string]$Color = "White")
    Write-Host $Text -ForegroundColor $Color
}

function Confirm-Prompt {
    param([string]$Message, [string]$Default = "y")
    $choice = Read-Host "$Message (y/n) [Default: $Default]"
    return if ($choice -eq "") { $Default -eq "y" } else { $choice -eq "y" }
}

function Select-FromList {
    param([string]$Title, [string[]]$Options, [int]$DefaultIndex = 0)
    Write-ColorText $Title Cyan
    for ($i = 0; $i -lt $Options.Count; $i++) {
        $marker = if ($i -eq $DefaultIndex) { "*" } else { " " }
        Write-Host "  $marker$($i+1). $($Options[$i])"
    }
    $choice = Read-Host "Please enter option (1-$($Options.Count)) [Default: $($DefaultIndex+1)]"
    $idx = if ($choice -eq "") { $DefaultIndex } else { [int]$choice - 1 }
    if ($idx -lt 0 -or $idx -ge $Options.Count) {
        throw "Invalid option"
    }
    return $idx
}

Write-ColorText "=== Liber Speech Interactive Setup ===" Green
Write-Host ""

# 1. Component selection
$compIdx = Select-FromList -Title "Please select components to install:" -Options @("Full (ASR+TTS+API)", "ASR only", "TTS only", "ASR+TTS (no API)", "Custom") -DefaultIndex 0
$components = switch ($compIdx) {
    0 { @("asr", "tts", "api") }
    1 { @("asr") }
    2 { @("tts") }
    3 { @("asr", "tts") }
    4 { 
        Write-ColorText "Custom components (space separated):" Cyan
        $custom = Read-Host "Available: asr tts api"
        $custom.Split(" ", [StringSplitOptions]::RemoveEmptyEntries)
    }
}
Write-Host "Selected components: $($components -join ', ')"

# 2. Device selection
$devIdx = Select-FromList -Title "Please select inference device:" -Options @("Auto detect", "CPU", "CUDA (GPU)") -DefaultIndex 0
$device = switch ($devIdx) {
    0 { "auto" }
    1 { "cpu" }
    2 { "cuda" }
}
Write-Host "Device: $device"

# 3. ASR model selection
$asrModel = "openai/whisper-large-v3"
if ($components -contains "asr") {
    $asrIdx = Select-FromList -Title "Please select ASR model:" -Options @(
        "openai/whisper-large-v3 (Recommended)",
        "openai/whisper-medium",
        "openai/whisper-small",
        "openai/whisper-base",
        "openai/whisper-tiny",
        "Custom"
    ) -DefaultIndex 0
    $asrModel = switch ($asrIdx) {
        0 { "openai/whisper-large-v3" }
        1 { "openai/whisper-medium" }
        2 { "openai/whisper-small" }
        3 { "openai/whisper-base" }
        4 { "openai/whisper-tiny" }
        5 { Read-Host "Please enter custom Whisper model name" }
    }
}

# 4. TTS model selection
$ttsModel = "multilingual"
if ($components -contains "tts") {
    $ttsIdx = Select-FromList -Title "Please select TTS model:" -Options @(
        "multilingual (Recommended)",
        "turbo (Speed priority)",
        "standard (Quality priority)",
        "Custom"
    ) -DefaultIndex 0
    $ttsModel = switch ($ttsIdx) {
        0 { "multilingual" }
        1 { "turbo" }
        2 { "standard" }
        3 { Read-Host "Please enter custom TTS model (turbo/standard/multilingual)" }
    }
}

# 5. API authentication configuration
$authMode = "api_key"
$apiKeys = @()
if ($components -contains "api") {
    $authIdx = Select-FromList -Title "Please select API authentication mode:" -Options @("API Key (Recommended)", "No authentication (Development only)") -DefaultIndex 0
    $authMode = switch ($authIdx) {
        0 { "api_key" }
        1 { "none" }
    }
    if ($authMode -eq "api_key") {
        $key = Read-Host "Please enter API Key (leave empty to auto-generate)"
        if ($key -eq "") {
            $key = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 32 | ForEach-Object { [char]$_ })
        }
        $apiKeys = @($key)
    }
}

# 6. Results directory and TTL
$resultsDir = "results"
$ttlHours = 24
if ($components -contains "api") {
    $resultsDir = Read-Host "Please enter async task results directory (Default: results)"
    if ($resultsDir -eq "") { $resultsDir = "results" }
    $ttlInput = Read-Host "Please enter result retention time (hours) (Default: 24)"
    if ($ttlInput -ne "") { $ttlHours = [int]$ttlInput }
}

# 7. HF cache directory
$hfCache = Read-Host "Please enter HuggingFace cache directory (leave empty for default)"
if ($hfCache -eq "") { $hfCache = "" }

# 8. Generate .env
$envLines = @(
    "# Liber Speech Environment Configuration",
    "# Auto-generated by setup.ps1",
    ""
)
if ($components -contains "asr") {
    $envLines += "LIBER_ASR_MODEL=$asrModel"
}
if ($components -contains "tts") {
    $envLines += "LIBER_TTS_MODEL=$ttsModel"
}
$envLines += "LIBER_DEVICE=$device"
if ($components -contains "api") {
    $envLines += "LIBER_API_AUTH_MODE=$authMode"
    if ($apiKeys.Count -gt 0) {
        $envLines += "LIBER_API_KEYS=$($apiKeys -join ',')"
    }
    $envLines += "LIBER_API_HOST=0.0.0.0"
    $envLines += "LIBER_API_PORT=5555"
    $envLines += "LIBER_RESULTS_DIR=$resultsDir"
    $envLines += "LIBER_RESULTS_TTL_HOURS=$ttlHours"
}
if ($hfCache -ne "") {
    $envLines += "LIBER_HF_CACHE_DIR=$hfCache"
}
$envLines += ""
$envLines += "# CLI Default Parameters"
$envLines += "LIBER_CLI_DEVICE=$device"

$envContent = $envLines -join [Environment]::NewLine
Set-Content -Path $ConfigFile -Value $envContent -Encoding UTF8
Write-Host ""
Write-ColorText "Configuration written to: $ConfigFile" Green

# 9. Install dependencies
Write-Host ""
Write-ColorText "Installing dependencies..." Cyan
$extraArgs = @()
if ($components -contains "api") {
    $extraArgs += "--extra", "api"
}
& uv sync @extraArgs
if ($LASTEXITCODE -ne 0) {
    throw "Dependency installation failed"
}
Write-ColorText "Dependencies installed successfully" Green

# 10. Verify installation
Write-Host ""
Write-ColorText "Verifying installation..." Cyan
& uv run liber-speech version
if ($LASTEXITCODE -ne 0) {
    Write-ColorText "CLI entry point abnormal, please check PATH or virtual environment" Yellow
} else {
    Write-ColorText "CLI entry point normal" Green
}

# 11. Complete
Write-Host ""
Write-ColorText "=== Installation Complete ===" Green
Write-Host "Configuration file: $ConfigFile"
Write-Host "Start CLI: uv run liber-speech --help"
if ($components -contains "api") {
    Write-Host "Start API: uv run liber-speech serve"
}
Write-Host ""
Write-ColorText "To reconfigure, delete $ConfigFile and run setup.ps1 again" Cyan
